### ISSUE TITLE
Hardcode AmsiOpenSession+0x4c doesn't work in my environment

### ISSUE THREAD

**Issue by bopin2020** [D1rkMtr/PatchThatAMSI#1]
Thanks for your project,but I found two little troubles code insides.
1. Patch array was not initialized,but with a default value by VC which will be full with 0xcc and lstrcatA doesn't work. More details,please check picture1 below
2. When patch code replaced original AmsiOpenSession+0x44 with AmsiOpenSession+0x4c, but at 0x4c offset we will meet int3,so it will crash  our process. check picture2 and picture3

BTW I tested win11 latest in early two hours.

[Picture1]
![image](https://user-images.githubusercontent.com/49940777/197367708-50562485-c6ce-444d-bbdd-d2a50fc663a9.png)

[Picture2]
![image](https://user-images.githubusercontent.com/49940777/197367721-d7de7199-786d-4f9e-9f17-6c1f28c2405c.png)
![image](https://user-images.githubusercontent.com/49940777/197367728-32fe2b0b-978d-4a32-9304-6e5d2229a79d.png)

**Comment by bopin2020** [comment]
change patch code : 

`	char Patch[100];
	ZeroMemory(Patch, 100);
	lstrcatA(Patch, "\x81\x39\x44\x31\x52\x4B\x75\x32");
`


![image](https://user-images.githubusercontent.com/49940777/197368142-61123bb3-462f-47b3-a0d1-757f173c94a0.png)

**Comment by D1rkMtr** [comment]
![Windows10](https://user-images.githubusercontent.com/110354855/197368466-f453d170-73a8-4087-83a5-57dd13f7bfc7.png)

**Comment by D1rkMtr** [comment]
it depends on the windows version , as you can see the assembly is quite different.
so the patch 1 and 2 work on windows10 not on windows11
but other patches3..6 work on both  i think

**Comment by bopin2020** [comment]
This trouble happened on **AMS1patch1** method,others not affected!
