### ISSUE TITLE
AMSI patch Research paper or references

### ISSUE THREAD

**Issue by a7t0fwa7** [D1rkMtr/PatchThatAMSI#2]
Hey Brother, great research on this, do you have a blog that walks through the process for finding these patches? or any references on where I can find these research methods?

**Comment by bopin2020** [comment]
=> https://i.blackhat.com/Asia-22/Friday-Materials/AS-22-Korkos-AMSI-and-Bypass.pdf

**Comment by D1rkMtr** [comment]
Sorry for the late :
https://amonsec.net/posts/2020/03/00000000/
https://amonsec.net/posts/2022/05/0000000c/
