### ISSUE TITLE
Option 5 Not Working

### ISSUE THREAD

**Issue by rootisareservedword** [D1rkMtr/PatchThatAMSI#3]
Great script. During my limited testing, option #5 did not seem to work.
![option5](https://user-images.githubusercontent.com/36577613/198850106-a7c0302f-579e-4267-be78-102da81718fd.png)

**Comment by D1rkMtr** [comment]
is it a windows 11 ? bcz this patching is fully compatible with win10 version, and the assembly of amsi in win11 version is a bit different, so Yeah , this is done for win10

**Comment by rootisareservedword** [comment]
My mistake. Yes, W11. Thanks.
